#! /bin/sh
. "${HOME}/.cache/wal/colors.sh"
${HOME}/.config/scripts/keyb_languages.sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "$color4"
#bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^9' state=floating follow=on

wal -R
pgrep -x polybar > /dev/null || $HOME/.config/scripts/start_polybar.sh &
pgrep -x redshift > /dev/null || redshift -l 54.68916:25.2798 &
(sleep 1 && xmodmap ${HOME}/.Xmodmap) &
# without waiting xmodmap won't load properly
pgrep -x picom > /dev/null || $HOME/.config/scripts/start_picom.sh &
pgrep -x xss-lock > /dev/null || xss-lock -n /usr/lib/xsecurelock/dimmer -l -- ~/.config/scripts/lock.sh
xset s 180 120
