#! /bin/sh
source "${HOME}/.cache/wal/colors.sh"
for script in ~/.startup/on_load/* ; do
	echo "executing onload script ${script}"
	$script
done
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
xrandr --output DP-1 --off --output HDMI-1 --primary --mode 1920x1080 --pos 3840x0 --rotate normal --output DVI-D-2 --off --output DVI-D-1 --mode 1920x1080 --pos 1920x0 --rotate normal
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DVI-D-1 -d B1 B2 B3 B4 B5 B6 B7 B8 B9 B10
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config border_width        1
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "$color4"
#bspc config active_border_color "$color2"
bspc config presel_feedback_color "$color2"
bspc config focused_border_color "$color1"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^6' state=floating follow=off
bspc rule -a "*:*:Picture-in-Picture" state=floating follow=off sticky=on rectangle=320x180+1600+880
bspc rule -a "*:*:scratch" state=floating follow=off sticky=on rectangle=420x280+1500+780
wal -R
pgrep -x redshift > /dev/null || redshift -l 54.68916:25.2798 &
pgrep -x picom > /dev/null || $HOME/.config/scripts/start_picom.sh &
pgrep -x xss-lock > /dev/null || xss-lock -n /usr/lib/xsecurelock/dimmer -l -- ~/.config/scripts/lock.sh
xset s 180 120
