#! /bin/sh
for script in ~/.startup/on_load/* ; do
	echo "executing onload script ${script}"
	$script
done

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config border_width        1
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^6' state=floating follow=off
bspc rule -a "*:*:Picture-in-Picture" state=floating follow=off sticky=on rectangle=320x180+1600+880
bspc rule -a "*:*:scratch" state=floating follow=off sticky=on rectangle=420x280+1500+780