#! /bin/sh
source "${HOME}/.cache/wal/colors.sh"
for script in ~/.startup/on_load/* ; do
	echo "executing onload script ${script}"
	$script
done

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config border_width        1
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "$color4"
#bspc config active_border_color "$color2"
bspc config presel_feedback_color "$color2"
bspc config focused_border_color "$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^6' state=floating follow=off
bspc rule -a "*:*:Picture-in-Picture" state=floating follow=off sticky=on rectangle=320x180+1600+880
bspc rule -a "*:*:scratch" state=floating follow=off sticky=on rectangle=420x280+1500+780

pgrep -x redshift > /dev/null || redshift -l 54.68916:25.2798 &
pgrep -x xss-lock > /dev/null || xss-lock -n /usr/lib/xsecurelock/dimmer -l -- ~/.config/scripts/lock.sh
xset s 180 120